make bonus
clear
echo ""
./miniRT maps/standard/error/err_amb_exists.rt
echo ""
./miniRT maps/standard/error/err_invalid_normal.rt
echo ""
./miniRT maps/standard/error/err_par_col.rt
echo ""
./miniRT maps/standard/error/err_par_delim.rt
echo ""
./miniRT maps/standard/error/err_par_ext.rttt
echo ""
./miniRT maps/standard/error/err_par_ext2
echo ""
./miniRT maps/standard/error/err_par_int.rt
echo ""
./miniRT maps/standard/error/err_par_noid.rt
echo ""
./miniRT maps/standard/error/err_par_real.rt
echo ""
./miniRT maps/standard/error/err_par_unit.rt
echo ""
./miniRT maps/standard/error/err_res_exists.rt
echo ""
./miniRT maps/standard/error/err_res_neg.rt
echo ""
./miniRT maps/standard/error/err_undef_cam.rt
echo ""
./miniRT maps/standard/error/err_undef_res.rt
echo ""
./miniRT maps/standard/error/err_unused_param.rt
echo ""
./miniRT maps/standard/error/err_vec_failure.rt
echo ""
./miniRT maps/standard/error/err_zero_normal.rt
echo ""
./miniRT maps/standard/error/warn_fov_range.rt
echo ""
./miniRT maps/standard/error/warn_res_max_res.rt
